services:
  hypertube:
    build: .

  caddy:
    image: caddy
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_logs:/var/log/caddy

include:
  - ./metrics/docker-compose.yml
