services:
  hypertube:
    build: app
    develop:
      watch:
        - action: rebuild
          path: app
          target: /app/

  caddy:
    image: caddy
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./metrics/data/caddy_logs:/var/log/caddy

  postgres:
    image: postgres
    env_file: .env
    volumes:
      - ./data:/var/lib/postgres/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_DB: hypertube
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    build: keycloak
    env_file: .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: keycloak.localhost
      KC_HTTP_ENABLED: true

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start
    depends_on:
      - postgres

  redis:
    image: redis

  meilisearch:
    image: getmeili/meilisearch

  smtp:
    image: rnwood/smtp4dev

include:
  - ./metrics/docker-compose.yml
