#!/bin/sh

PGPASSWORD="$ROOT_DB_PASSWORD" psql -U root <<EOF
CREATE DATABASE keycloak;
CREATE USER keycloak WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
ALTER DATABASE keycloak OWNER to keycloak;

CREATE DATABASE hypertube;
CREATE USER hypertube WITH ENCRYPTED PASSWORD '$HYPERTUBE_DB_PASSWORD';
ALTER DATABASE hypertube OWNER to hypertube;
EOF
