#!/bin/sh

PGPASSWORD="$ROOT_DB_PASSWORD" psql -U root <<EOF
CREATE DATABASE keycloak;
CREATE USER keycloak WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
ALTER DATABASE keycloak OWNER to keycloak;

CREATE DATABASE crocotube;
CREATE USER crocotube WITH ENCRYPTED PASSWORD '$HYPERTUBE_DB_PASSWORD';
ALTER DATABASE crocotube OWNER to crocotube;

CREATE DATABASE meilisearch;
CREATE USER meilisearch WITH ENCRYPTED PASSWORD '$MEILISEARCH_DB_PASSWORD';
ALTER DATABASE meilisearch OWNER to meilisearch;
ALTER USER meilisearch REPLICATION;
EOF
