progress:
  type: file

source:
  type: postgres
  host: postgres
  port: 5432
  user: meilisearch
  password: ${MEILISEARCH_DB_PASSWORD}
  database: meilisearch

meilisearch:
  api_url: http://meilisearch:7700
  api_key:

sync:
  - table: content
