services:
  # to display statistics and logs from prometheus and loki
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      # later, the authentication should be
      # handled by keycloak
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - metrics
      - default

  # to gather statistics (from e.g. caddy)
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics
      - default

  # to send caddy logs (received from promtail) to grafana
  loki:
    image: grafana/loki
    networks:
      - metrics
      - default

  # to send caddy logs to loki
  promtail:
    image: grafana/promtail
    volumes:
      - ./data/caddy_logs:/var/log/caddy
      - ./promtail.yml:/etc/promtail/config.yml
    networks:
      - metrics
      - default

  # to gather host system usage
  node_exporter:
    image: prom/node-exporter
    command:
      - --path.rootfs=/host
      - --collector.systemd
      - --collector.processes
    pid: host
    volumes:
      - /:/host:ro,rslave
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/var/run/dbus/system_bus_socket
    networks:
      - metrics
      - default

networks:
  # allows node-exporter to access host network usage
  metrics:
    driver: bridge
